case_mappings:
  waf:
  cloudfront:
    file: '../data/reference_cloudfront.json'
menu_options:
  waf:
    DisplayName: 'AWS WAF'
    ResourceTypes:
      - 'AWS::WAFv2::WebACL'
    ServiceName: 'wafv2'
  cloudfront:
    DisplayName: 'AWS Cloudfront'
    ResourceTypes:
      - 'AWS::CloudFront::Distribution'
    ServiceName: 'cloudfront'